-- MySQL Script generated by MySQL Workbench
-- 04/06/16 04:53:39
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rg_tk
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS rg_tk ;
CREATE SCHEMA IF NOT EXISTS rg_tk DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE rg_tk ;

-- -----------------------------------------------------
-- Table rg_tk.sede
-- -----------------------------------------------------
DROP TABLE IF EXISTS rg_tk.sede ;

CREATE TABLE IF NOT EXISTS rg_tk.sede (
  codigo INT NOT NULL,
  nombre VARCHAR(45) NOT NULL,
  direccion VARCHAR(45) NOT NULL,
  PRIMARY KEY (codigo))
ENGINE = InnoDB;